version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: synergysphere
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - synergysphere-network

  # Backend API
  backend:
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://root:password123@mongodb:27017/synergysphere?authSource=admin
      - JWT_SECRET=super-secret-jwt-key-change-in-production
      - JWT_REFRESH_SECRET=super-secret-refresh-key-change-in-production
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./logs:/app/logs
    networks:
      - synergysphere-network

  # Frontend (optional - if you want to run frontend in Docker too)
  frontend:
    build: ../frontend
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - synergysphere-network

volumes:
  mongodb_data:

networks:
  synergysphere-network:
    driver: bridge
